version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: dockerfile
      args: 
        - IRIS_PASSWORD=$IRIS_PASSWORD
    command: --check-caps false
    restart: always
    env_file: 
      - .env
    ports: 
      - 45450:1972
      - 45451:52773
      - 45452:53773
    volumes:
      - ./:/opt/irisapp
      - ./misc/aws/:/home/irisowner/.aws/ 

  localstack:
    image: localstack/localstack
    container_name: localstack-container1
    ports:
      - "4566-4599:4566-4599"
    environment:
      - REGION='us-east-1'
      - SERVICES=dynamodb,s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID='123'
      - AWS_SECRET_KEY='xyz'